### ISSUE TITLE
Are you using this?

### ISSUE THREAD

**Issue by psiho** [pchwalek/insta360_ble_esp32#1]
This is a great idea. Shutter and wakeup are basically all I need. But before diving into this and program buttons and indicators, designing and printing the case... have you tried this in practice? It's a lot of work just to check reliability of it :) I'd be willing to work on 3d printable case and some software updates for screen and/or LED indicators... but would hate to dive this deep only to find out connection is not reliable.

EDIT: well, this seems incomplete. Missing startAdvertisingWithManufData()

**Comment by pchwalek** [comment]
Apologies for the massive delay but I'm in the last year of my PhD so things are busy. I haven't yet deployed this in a complete system but I've lab tested it and it seems stable. 

I included the files in the latest commit. Just replace the core Arduino ESP32 files with the modified versions.
